name: Checks
on:
  push:
  pull_request:
jobs:
  scalafix:
    name: Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt "scalafix --check" "Test / scalafix --check"
  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: ./bin/scalafmt --check
  headers:
    name: Copyright headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt "+ headerCheck" "+ Test / headerCheck"
